# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-31 21:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('contenido', tinymce.models.HTMLField()),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Articulo',
                'verbose_name_plural': 'Articulos',
            },
        ),
        migrations.CreateModel(
            name='Catalogo_Preguntas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('id_reactivo', models.CharField(max_length=200)),
                ('bloque', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Catalogo_Preguntas',
                'verbose_name_plural': 'Catalogo_Preguntas',
            },
        ),
        migrations.CreateModel(
            name='Corte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_de_corte', models.DateTimeField(null=True)),
                ('aprovado', models.NullBooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Cuestionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('website_corporativo', models.URLField(max_length=1000)),
                ('website_integridad', models.URLField(max_length=1000)),
                ('tot100', models.CharField(blank=True, max_length=255, null=True)),
                ('tot', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
            },
        ),
        migrations.CreateModel(
            name='Fuentes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('libro', models.CharField(max_length=255)),
                ('url', models.URLField(blank=True, default='', max_length=500)),
            ],
            options={
                'verbose_name': 'Fuente',
                'verbose_name_plural': 'Fuentes',
                'ordering': ['titulo'],
            },
        ),
        migrations.CreateModel(
            name='Glosario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField(null=True)),
            ],
            options={
                'verbose_name': 'Glosario',
                'verbose_name_plural': 'Glosarios',
                'ordering': ['titulo'],
            },
        ),
        migrations.CreateModel(
            name='Paises',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pais', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Pais',
                'verbose_name_plural': 'Paises',
                'ordering': ['pais'],
            },
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reactivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mxvscorrupcion.Catalogo_Preguntas')),
            ],
        ),
        migrations.CreateModel(
            name='Respuestas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(max_length=3)),
                ('opcion', models.CharField(max_length=200)),
                ('catalogo_pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mxvscorrupcion.Catalogo_Preguntas')),
            ],
        ),
        migrations.CreateModel(
            name='Sectores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Sector',
                'verbose_name_plural': 'Sectores',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='pregunta',
            name='respuesta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mxvscorrupcion.Respuestas'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mxvscorrupcion.Paises'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mxvscorrupcion.Sectores'),
        ),
        migrations.AddField(
            model_name='cuestionario',
            name='Empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mxvscorrupcion.Empresa'),
        ),
        migrations.AddField(
            model_name='cuestionario',
            name='preguntas',
            field=models.ManyToManyField(to='mxvscorrupcion.Pregunta'),
        ),
        migrations.AddField(
            model_name='corte',
            name='cuestionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mxvscorrupcion.Cuestionario'),
        ),
    ]
