# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-27 22:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mxvscorrupcion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='cuestionario',
        ),
        migrations.RemoveField(
            model_name='sectores',
            name='extra',
        ),
        migrations.RemoveField(
            model_name='sectores',
            name='extras',
        ),
        migrations.AddField(
            model_name='cuestionario',
            name='Empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mxvscorrupcion.Empresa'),
            preserve_default=False,
        ),
    ]
