# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-14 18:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mxvscorrupcion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregunta',
            name='status',
            field=models.CharField(blank=True, choices=[('0', 'En espera para revisión'), ('1', 'Aprovada'), ('2', 'Rechazda')], default='0', max_length=3, null=True),
        ),
    ]
