# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-20 17:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mxvscorrupcion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='cuestionario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mxvscorrupcion.Cuestionario'),
        ),
    ]
