# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-25 01:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mxvscorrupcion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Corte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_de_corte', models.DateTimeField(null=True)),
                ('aprovado', models.NullBooleanField()),
                ('cuestionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mxvscorrupcion.Cuestionario')),
            ],
        ),
        migrations.AlterModelOptions(
            name='catalogo_preguntas',
            options={'verbose_name': 'Catalogo_Preguntas', 'verbose_name_plural': 'Catalogo_Preguntas'},
        ),
    ]
