# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-26 21:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mxvscorrupcion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='nombre',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='website_corporativo',
            field=models.URLField(max_length=255),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='website_integridad',
            field=models.URLField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='paises',
            name='pais',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='respuesta',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='text_pregunta',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='sectores',
            name='nombre',
            field=models.CharField(max_length=255),
        ),
    ]
