# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-07 17:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mxvscorrupcion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entradas_Recientes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('fecha', models.CharField(max_length=50)),
                ('url', models.URLField(blank=True, default='', max_length=500)),
            ],
            options={
                'verbose_name': 'Entrada_Reciente',
                'verbose_name_plural': 'Entradas_Recientes',
            },
        ),
    ]
