# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-25 01:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mxvscorrupcion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='slug',
            field=models.SlugField(max_length=255, null=True, unique=True),
        ),
    ]
