# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-27 18:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mxvscorrupcion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respuestas',
            name='opcion',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='respuestas',
            name='valor',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
