# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-15 04:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mxvscorrupcion', '0002_auto_20171114_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='respuestas',
            name='evidencia',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pregunta_rechazada',
            name='motivo',
            field=models.CharField(choices=[('0', 'Seleccione un motivo'), ('1', 'La información es insuficiente'), ('2', 'El enlace está roto/ no hay enlace'), ('3', 'La información no corresponde al apartado'), ('4', 'Otro (especificar)')], default='0', max_length=3),
        ),
    ]
