# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-07 18:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mxvscorrupcion', '0002_entradas_recientes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entradas_recientes',
            name='fecha',
            field=models.DateField(),
        ),
    ]
