# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-26 22:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mxvscorrupcion', '0002_auto_20170926_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='website_corporativo',
            field=models.URLField(max_length=1000),
        ),
    ]
