# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-09 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mxvscorrupcion', '0003_auto_20171107_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='autor',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='articulo',
            name='url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
