# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-16 17:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mxvscorrupcion', '0003_auto_20171115_0410'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='extencion',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='telefono_celular',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='telefono_fijo',
            field=models.CharField(max_length=10),
        ),
    ]
