# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-25 21:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mxvscorrupcion', '0003_auto_20171025_0154'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='tot',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='tot100',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
