# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-09 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mxvscorrupcion', '0003_auto_20171109_1512'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfil',
            old_name='telefono',
            new_name='telefono_fijo',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='tel_type',
        ),
        migrations.AddField(
            model_name='perfil',
            name='telefono_celular',
            field=models.CharField(default='', max_length=12),
            preserve_default=False,
        ),
    ]
