# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-26 14:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mxvscorrupcion', '0004_auto_20171025_2102'),
    ]

    operations = [
        migrations.CreateModel(
            name='Glosario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Glosario',
                'verbose_name_plural': 'Glosarios',
                'ordering': ['title'],
            },
        ),
    ]
