# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-16 17:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mxvscorrupcion', '0004_auto_20171116_1702'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfil',
            old_name='extencion',
            new_name='extension',
        ),
    ]
