# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-25 00:39
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('mxvscorrupcion', '0005_articulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='contenido',
            field=tinymce.models.HTMLField(),
        ),
    ]
