# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-26 02:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mxvscorrupcion', '0005_catalogo_preguntas_id_reactivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Respuestas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=5)),
                ('opcion', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='catalogo_preguntas',
            name='respuestas',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mxvscorrupcion.Respuestas'),
            preserve_default=False,
        ),
    ]
