# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-26 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mxvscorrupcion', '0005_glosario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glosario',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
