# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-26 03:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mxvscorrupcion', '0006_auto_20171026_0251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respuestas',
            name='valor',
            field=models.DecimalField(choices=[('1', 'Awaiting'), ('2', 'No'), ('3', 'Yes')], decimal_places=2, max_digits=5),
        ),
    ]
