# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-26 15:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mxvscorrupcion', '0006_auto_20171026_1431'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fuentes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('libro', models.CharField(max_length=255)),
                ('url', models.URLField(blank=True, default='', max_length=500)),
            ],
            options={
                'verbose_name': 'Fuente',
                'verbose_name_plural': 'Fuentes',
                'ordering': ['titulo'],
            },
        ),
        migrations.AlterModelOptions(
            name='glosario',
            options={'ordering': ['titulo'], 'verbose_name': 'Glosario', 'verbose_name_plural': 'Glosarios'},
        ),
        migrations.RenameField(
            model_name='glosario',
            old_name='description',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='glosario',
            old_name='title',
            new_name='titulo',
        ),
    ]
