# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-26 03:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mxvscorrupcion', '0007_auto_20171026_0303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respuestas',
            name='valor',
            field=models.DecimalField(choices=[('0', 0), ('0.5', 0.5), ('1', 1)], decimal_places=2, max_digits=5),
        ),
    ]
