# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-10 15:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mxvscorrupcion', '0007_articulo_revista'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articulo',
            name='revista',
        ),
    ]
