# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-10 16:07
from __future__ import unicode_literals

from django.db import migrations
import django.utils.timezone
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('mxvscorrupcion', '0008_remove_articulo_revista'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='revista',
            field=tinymce.models.HTMLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
