# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-26 03:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mxvscorrupcion', '0008_auto_20171026_0305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respuestas',
            name='valor',
            field=models.CharField(choices=[('0', '0'), ('0.5', '0.5'), ('1', '1')], max_length=3),
        ),
    ]
