# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-26 03:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mxvscorrupcion', '0009_auto_20171026_0306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalogo_preguntas',
            name='respuestas',
        ),
        migrations.AddField(
            model_name='respuestas',
            name='Pregunta',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='mxvscorrupcion.Catalogo_Preguntas'),
            preserve_default=False,
        ),
    ]
