# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-10 16:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mxvscorrupcion', '0009_articulo_revista'),
    ]

    operations = [
        migrations.AddField(
            model_name='entradas_recientes',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
