# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-26 03:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mxvscorrupcion', '0010_auto_20171026_0309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregunta',
            name='respuesta',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mxvscorrupcion.Respuestas'),
            preserve_default=False,
        ),
    ]
