# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-10 18:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mxvscorrupcion', '0005_auto_20171110_1610'),
        ('mxvscorrupcion', '0010_entradas_recientes_imagen'),
    ]

    operations = [
    ]
