# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-12 10:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mxvscorrupcion', '0011_merge_20171110_2019'),
        ('mxvscorrupcion', '0011_merge_20171110_1807'),
    ]

    operations = [
    ]
