# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-12 10:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mxvscorrupcion', '0012_merge_20171112_1005'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pregunta_temporal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reactivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mxvscorrupcion.Catalogo_Preguntas')),
            ],
        ),
        migrations.RemoveField(
            model_name='respuestas',
            name='catalogo_pregunta',
        ),
        migrations.AddField(
            model_name='pregunta_temporal',
            name='respuesta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mxvscorrupcion.Respuestas'),
        ),
    ]
