# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-12 20:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mxvscorrupcion', '0013_auto_20171112_1005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='corte',
            name='cuestionario',
        ),
        migrations.AddField(
            model_name='cuestionario',
            name='Corte',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mxvscorrupcion.Corte'),
            preserve_default=False,
        ),
    ]
