# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-13 02:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mxvscorrupcion', '0015_auto_20171113_0200'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuestionario',
            name='Corte',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mxvscorrupcion.Corte'),
            preserve_default=False,
        ),
    ]
