# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-14 00:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mxvscorrupcion', '0016_cuestionario_corte'),
    ]

    operations = [
        migrations.AddField(
            model_name='respuestas',
            name='catalogo_pregunta',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mxvscorrupcion.Catalogo_Preguntas'),
            preserve_default=False,
        ),
    ]
