# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-13 21:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mxvscorrupcion', '0016_cuestionario_corte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corte',
            name='fecha_de_corte',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='cuestionario',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
