# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-13 22:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mxvscorrupcion', '0016_cuestionario_corte'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pregunta_Rechazada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(choices=[('1', 'Primer motivo'), ('2', 'segundo motivo'), ('3', 'tercer motivo'), ('4', 'cuarto motivo'), ('5', 'quinto motivo')], default='1', max_length=3)),
                ('respuestaPersonalizada', models.CharField(max_length=300)),
                ('comentarios', models.CharField(max_length=300)),
            ],
        ),
    ]
