# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-14 04:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mxvscorrupcion', '0017_auto_20171113_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='respuestas',
            name='catalogo_pregunta',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mxvscorrupcion.Catalogo_Preguntas'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='corte',
            name='fecha_de_corte',
            field=models.DateField(null=True, unique_for_date=True),
        ),
    ]
