# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-13 22:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mxvscorrupcion', '0017_pregunta_rechazada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregunta_rechazada',
            name='comentarios',
            field=models.TextField(),
        ),
    ]
