# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-13 22:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mxvscorrupcion', '0018_auto_20171113_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregunta',
            name='comentarios',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mxvscorrupcion.Pregunta_Rechazada'),
        ),
        migrations.AlterField(
            model_name='pregunta_rechazada',
            name='comentarios',
            field=models.TextField(null=True),
        ),
    ]
